---
title: "Corona Virus Report"
author:
- familyname: XXXX
  othernames: XXX
  address: Monash University
  email: XXX
  correspondingauthor: true
  qualifications:  XXX
- familyname: XXXX
  othernames: Reports
  address: XXX
  qualifications: XXX
- familyname: XXX
  othernames: XXX
  address: XXX
  email: XXX
  correspondingauthor: true
  qualifications:  XXX
department: Our consultancy \newline add names &\newline add names
organization: Australian Government COVID19
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  bookdown::pdf_document2:
    template: monashreport2.tex
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: false
---

```{r , echo = FALSE, message = FALSE, warning = FALSE}
# Libraries

library(tidyverse)
library(readr)
library(kableExtra)
library(bookdown)
library(ggplot2)

```



\section*{Country XX1 and YY1"}

\section*{Country XX2 and YY2}

```{r read in data section 2}
covidsection2 <- read_csv("Data/worldwidecases.csv")
```

```{r filter for section 2 countries}
france_italy <- covidsection2 %>%
  filter(countriesAndTerritories %in% c("France", "Italy"))
```

```{r count cases and deaths for france and italy}
france_italy_cases <- france_italy %>%
  group_by(countriesAndTerritories) %>%
  tally(cases) %>%
  rename("cases" = n, "countries" = countriesAndTerritories)

france_italy_deaths <- france_italy %>%
  group_by(countriesAndTerritories) %>%
  tally(deaths) %>%
  rename("deaths" = n, "countries" = countriesAndTerritories)
```

```{r join cases and deaths dataframes}
france_italy_combined <- france_italy_cases %>%
  left_join(france_italy_deaths)
```

```{r create summary table}
france_italy_combined %>% 
  kable(caption = "France and Italy: Total cases and deaths as of 10 May 2020") %>%
  kable_styling(bootstrap_options = "striped")
```

Table \@ref(tab: create summary table) shows the total number of cases and deaths in France and Italy respectively, as of 10 May 2020. 

The total number of cases and deaths in both countries is plotted in Figure \@ref(fig: total plot)

```{r total plot, fig.cap = "France and Italy: Total cases and deaths as of 10 May 2020"}

france_italy_combined %>%
  ggplot(aes(x = countries, y = as.numeric(cases))) +
  geom_bar(stat = "identity") +
  labs(y = "cases")
```


\section*{Country XX3 and YY3}



